"""empty message

Revision ID: 714325ea1153
Revises: 76abb4fa3cb6
Create Date: 2020-08-29 21:23:57.398098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714325ea1153'
down_revision = '76abb4fa3cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hobby', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hobby')
    # ### end Alembic commands ###
