"""empty message

Revision ID: e37407c143e6
Revises: 6ef14df292bd
Create Date: 2020-08-29 23:05:48.879684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37407c143e6'
down_revision = '6ef14df292bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_delete')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
